---
title: "Lists - In Class Exercises"
author: "Dr. Shoemaker"
date: "DATA 2401"
output:nhtml_document

---

# Exercises: 

Make a list that contains the information on a single playing card. Suit, face, and value. 

```{r}

one_card = list(
  suit = "diamond",
  face = "king",
  value = 10
  
)


```


Make a second list where each element contains all the options for suit, face, and value, respectively. 

```{r}


all_card = list(
  suit = c("diamond", "spade", "heart", "club"),
  face = c("king", "queen", "jack", "ace", 1:10),
  value = c(10, 10, 10, 10, 1:10)
  
)


```


If `Newlist <- list(a=1:10, b="Good morning", c="Hi")`, write an R statement that will add 1 to each element of the first vector in Newlist.

```{r}
Newlist <- list(a=1:10, b="Good morning", c="Hi")

Newlist[[1]] <- Newlist[[1]] + 1
#Newlist$a <- Newlist$a + 1


```

If `b <- list(a=1:10, c="Hello", d="AA")`, write an R expression that will get all elements of the first vector of b, except the second, and write another that returns only elements of `a` that are greater than 7.

```{r}
b <- list(a=1:10, c="Hello", d="AA")

print(b$a[-2])

print(b$a[b$a > 7])

```

Let `x <- list(a=5:10, c="Hello", d="AA")`, write an R statement to add a new item z = "NewItem" to the list x.

```{r}
x <- list(a=5:10, c="Hello", d="AA")

x$z <- "NewItem"

```
